name: "Test in workspace"
on: [push, pull_request]
jobs:
  test-coverage:
    name: Run tests and generate coverage report
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: write
    steps:
      - name: Clone workspace
        uses: actions/checkout@v3
        with:
          repository: biothings/bte-trapi-workspace

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Install workspace with PR
        # checkout all same-named branches for cases of multi-PR dependent features
        run: |
          npm run clone
          npm run git remote set-url origin git@github.com:biothings/$(basename $(git remote get-url origin))
          npm run git checkout ${{ steps.branch-name.outputs.current_branch }}
          npm i || true && npm i

      - name: Get PR number (for activate on push)
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Run tests, generate coverage report
        id: coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./packages/@biothings-explorer/api-response-transform
          prnumber: ${{ steps.findPr.outputs.number }}
          skip-step: install
          test-script: npm run test-cov
          output: report-markdown

      - name: Comment report on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}

      - name: Generate badge
        uses: tokebe/jest-badges-action@master
        with:
          branches: main,jest-actions
          # coverage-summary-path: ./packages/@biothings-explorer/api-response-transform/coverage/coverage-summary.json
          working-directory: ./packages/@biothings-explorer/api-response-transform
